#!/usr/bin/python3

import os
import sys

is_group_1 = False
curr_branch = os.popen("git rev-parse --abbrev-ref HEAD").readline().strip()

if is_group_1 and curr_branch[0:2] == "g2":
    print("You are group1 and trying to commit on group2 branch!!")
    sys.exit(-1)

if not is_group_1 and curr_branch[0:2] == "g1": 
    print("You are group2 and trying to commit on group1 branch!!")
    sys.exit(-1)
