
name: G1-pipeline

on:
  push:
    branches: [ "g1-main" ]
  pull_request:
    branches: [ "g1-main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm install --force

            - name: Build
              run: npm run build
    
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm install --force

            - name: Test
              run: npm test