name: G2-pipeline

on:
  push:
    branches: [ "g2-main" ]
  pull_request:
    branches: [ "g2-main" ]

jobs:
  initial-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test
  dawload_clinglo: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Installing Clingo
        run: python3 -m pip install --user --upgrade clingo
        

  build:
    runs-on: ubuntu-latest
    needs: initial-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Svelte Project
        run: npm run build

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: svelte-artifacts
          path: build
  
