# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "g2-main" ]
  pull_request:
    branches: [ "g2-main" ]

jobs:
  initial-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test

  build-and-upload:
      runs-on: ubuntu-latest
      needs: [test]

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '14'
        - run: npm install
        - run: npx svelte-kit build 
        - run: mkdir -p build-output
        - run: cp -r build/* build-output/
        - uses: actions/upload-artifact@v3
          with:
            name: build
            path: g2/build

  testing-the-build:
      runs-on: ubuntu-latest
      needs: [build-and-upload]
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '14'
        - uses: actions/download-artifact@v3
          with:
            name: build
        - name: Display structure of downloaded files
          run: ls -R
        - run: npm install
        - run: npm test

